#!/usr/bin/env python3
"""
Builds the WoW Forever gear tables from the curated JSON:

  web/scripts/forever-lvl30.json  ->  TBCBisTracker/Database_Forever.lua  (add-on)
                                  ->  web/public/data/forever.js          (website)

Entries without an item ID are kept as comments (the add-on needs real IDs).
Run from anywhere; paths are resolved relative to the repo root.
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
SRC = REPO / "web" / "scripts" / "forever-lvl30.json"
OUT = REPO / "TBCBisTracker" / "Database_Forever.lua"
WEB_OUT = REPO / "web" / "public" / "data" / "forever.js"
PKG_FILE = REPO / "web" / "package.json"
TOC_FILE = REPO / "TBCBisTracker" / "TBCBisTracker.toc"

# Mirrors Forever.lua (FOREVER_PHASES / labels / descriptions).
PHASE_LABEL = "Level 30"
PHASE_DESCRIPTION = "Level 30 — beta cap: dungeons, quests, crafted and world drops"
SLOT_LABELS = {
    "head": "Head", "neck": "Neck", "shoulder": "Shoulders", "back": "Back",
    "chest": "Chest", "wrist": "Wrist", "hands": "Hands", "waist": "Waist",
    "legs": "Legs", "feet": "Feet", "ring1": "Ring 1", "ring2": "Ring 2",
    "trinket1": "Trinket 1", "trinket2": "Trinket 2", "mainhand": "Main Hand",
    "offhand": "Off Hand", "ranged": "Ranged",
}

PHASE = "lvl30"
CLASS_ORDER = ["WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST",
               "SHAMAN", "MAGE", "WARLOCK", "DRUID"]
SLOTS = ["head", "neck", "shoulder", "back", "chest", "wrist", "hands",
         "waist", "legs", "feet", "ring1", "ring2", "trinket1", "trinket2",
         "mainhand", "offhand", "ranged"]
SOURCE_TYPES = {"dungeon", "quest", "crafted", "world", "reputation", "pvp", "raid"}


def lua_str(s):
    if s is None:
        return "nil"
    s = str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    return '"' + s + '"'


def source_text(e):
    src = e.get("source") or "Unknown"
    name = e.get("name")
    if name and name not in src:
        src = "%s (%s)" % (src, name)
    return src


def source_type(e):
    return e.get("sourceType") if e.get("sourceType") in SOURCE_TYPES else "world"


def write_web(doc):
    """Same bundle shape as data.js (window.TBC_DATA), one phase: lvl30."""
    database = {}
    for cls, specs in doc["data"].items():
        for spec, slots in specs.items():
            out = {}
            for slot in SLOTS:
                items = []
                for e in slots.get(slot) or []:
                    if not e.get("id"):
                        continue
                    it = {"id": int(e["id"]), "source": source_text(e), "sourceType": source_type(e),
                          "note": e.get("note"), "questId": None}
                    if e.get("faction") in ("Alliance", "Horde"):
                        it["faction"] = e["faction"]
                    if e.get("sourceUrl"):
                        it["sourceUrl"] = e["sourceUrl"]
                    items.append(it)
                if items:
                    out[slot] = items
            database.setdefault(cls, {})[spec] = {PHASE: out}

    version = json.loads(PKG_FILE.read_text(encoding="utf-8")).get("version")
    addon_version = None
    for line in TOC_FILE.read_text(encoding="utf-8").splitlines():
        if line.startswith("## Version:"):
            addon_version = line.split(":", 1)[1].strip()
    bundle = {
        "database": database,
        "statCaps": {},
        "meta": {
            "slots": SLOTS,
            "phases": [PHASE],
            "slotLabels": SLOT_LABELS,
            "phaseLabels": {PHASE: PHASE_LABEL},
            "phaseDescriptions": {PHASE: PHASE_DESCRIPTION},
        },
        "version": version,
        "addonVersion": addon_version,
    }
    WEB_OUT.write_text(
        "/* Generated by web/scripts/build-forever-db.py — do not edit. */\n"
        "window.FOREVER_DATA = " + json.dumps(bundle, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print("wrote %s" % WEB_OUT.relative_to(REPO))


def main():
    doc = json.loads(SRC.read_text(encoding="utf-8"))
    data = doc["data"]
    meta = doc.get("meta", {})
    basis = doc.get("specBasis", {})

    lines = [
        "-- TBCBisTracker WoW Forever database (GENERATED — do not edit by hand)",
        "-- Source: web/scripts/forever-lvl30.json via web/scripts/build-forever-db.py",
        "-- Generated: " + str(meta.get("generated", "?")),
        "-- Beta data (level 30 cap): unverified until the game launches.",
        "",
        "TBCBisTracker = TBCBisTracker or {}",
        "TBCBisTracker.FOREVER_DB = {}",
        "",
        "local DB = TBCBisTracker.FOREVER_DB",
        "",
        "local function item(id, source, sourceType, note, faction)",
        '    return { id = id, source = source, sourceType = sourceType or "dungeon", note = note, faction = faction }',
        "end",
        "",
    ]

    total = with_id = 0
    for cls in CLASS_ORDER:
        specs = data.get(cls) or {}
        lines.append("-- " + "=" * 60)
        lines.append("-- " + cls)
        lines.append("-- " + "=" * 60)
        lines.append('DB["%s"] = {}' % cls)
        for spec, slots in specs.items():
            b = basis.get("%s/%s" % (cls, spec))
            if b:
                lines.append("-- %s: %s" % (spec, b))
            lines.append('DB["%s"][%s] = { %s = {' % (cls, lua_str(spec), PHASE))
            for slot in SLOTS:
                entries = slots.get(slot) or []
                if not entries:
                    continue
                body = []
                for e in entries:
                    total += 1
                    st = source_type(e)
                    src = source_text(e)
                    if not e.get("id"):
                        body.append("        -- no item ID yet: %s" % src.replace("\n", " "))
                        continue
                    with_id += 1
                    faction = e.get("faction") if e.get("faction") in ("Alliance", "Horde") else None
                    args = [str(int(e["id"])), lua_str(src), lua_str(st), lua_str(e.get("note"))]
                    if faction:
                        args.append(lua_str(faction))
                    body.append("        item(%s)," % ", ".join(args))
                if any(not l.lstrip().startswith("--") for l in body):
                    lines.append("    %s = {" % slot)
                    lines.extend(body)
                    lines.append("    },")
                else:
                    lines.extend(l.replace("        ", "    ", 1) for l in body)
            lines.append("} }")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s — %d entries, %d with item IDs" % (OUT.relative_to(REPO), total, with_id))
    write_web(doc)


if __name__ == "__main__":
    main()
